routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
});
Route::get('/home', function () {
    return view('dashboard');
});
Auth::routes();

Route::group(['middleware' => 'auth','prefix' => 'stock'], function ()
{
    Route::get('gsdgsgdsassssagas','StockController@customer')->name('customer');
    Route::get('book','BookController@book')->name('book');
    Route::get('booklist','BookController@index')->name('booklist');
    Route::post('addbook','BookController@addbook')->name('addbook');
    Route::get('purchasebook','StockController@purchasebook')->name('purchasebook');
    Route::post('addpurchasebook','StockController@addpurchasebook')->name('addpurchasebook');
    Route::post('addcustomer','StockController@addcustomer')->name('addcustomer');
    // Para controller
    Route::get('para','ParaController@para')->name('para');
    Route::get('paralist','ParaController@index')->name('paralist');
    Route::post('addpara','ParaController@addpara')->name('addpara');
    Route::get('purchasepara','ParaController@purchasepara')->name('purchasepara');
    Route::post('addpurchasepara','ParaController@addpurchasepara')->name('addpurchasepara');
   // sales book controller
   Route::get('salebook','Salesbookcontroller@salebook')->name('salebook');
    Route::post('addsalebook','Salesbookcontroller@addsalebook')->name('addsalebook');
    // sales para controller
   Route::get('salepara','Salesparacontroller@salepara')->name('salepara');
   Route::post('addsalepara','Salesparacontroller@addsalepara')->name('addsalepara');
    //refund of book
   Route::get('refundbook','RefundbookController@rb')->name('rb');
   Route::post('addrefundbook','RefundbookController@arb')->name('arb');
   //refund of Para
   Route::get('refundpara','RefundparaController@rp')->name('rp');
   Route::post('addrefundpara','RefundparaController@arp')->name('arp');
   //Waste  of book
   Route::get('wastebook','TransferbookController@tb')->name('tb');
   Route::post('addwastebook','TransferbookController@atb')->name('atb');
    //Waste  of para
   Route::get('wastepara','TransferparaController@tp')->name('tp');
   Route::post('addwastepara','TransferparaController@atp')->name('atp');
   // book report
   Route::get('abl','BookreportController@inq')->name('bookinq');
   Route::post('allbookbalance','BookreportController@all')->name('allbook');
   //para report
         Route::get('apl','ParareportController@inq')->name('parainq');
      Route::post('allparabalance','ParareportController@all')->name('allpara');
    //customer status
    Route::get('stat','CustomerStatusController@stat')->name('stat');
    Route::post('status','CustomerStatusController@status')->name('status');
    //invoice 
     Route::get('bookinvoice','InvoiceController@book')->name('bookinvoice');
     Route::get('parainvoice','InvoiceController@para')->name('parainvoice');
});

Route::group(['middleware' => 'auth','prefix' => 'account'], function ()
{
    //Department Controller
    Route::get('dep','DepartmentController@dep')->name('dep');
    Route::get('deplist','DepartmentController@index')->name('depindex');
    Route::post('adddep','DepartmentController@adddep')->name('adddep');
    //Ledger Controller
    Route::get('led','LedgerController@led')->name('led');
    Route::get('ledlist','LedgerController@index')->name('ledindex');
    Route::post('addled','LedgerController@addled')->name('addled');
    //Transection Controller
    Route::get('tran','TransectionController@tran')->name('tran');
    Route::post('addtran','TransectionController@addtran')->name('addtrans');
    //journal controller
    Route::get('journal','JournalController@journal')->name('journal');
    Route::post('addjournal','JournalController@addjournal')->name('addjournal');
    //payment controller
    Route::get('payment','PaymentController@payment')->name('payment');
    Route::post('addpayment','PaymentController@addpayment')->name('addpayment');
    //Received controller
    Route::get('received','ReceivedController@received')->name('received');
    Route::post('addreceived','ReceivedController@addreceived')->name('addreceived');
    //Contra controller
    Route::get('contra','ContraController@contra')->name('contra');
    Route::post('addcontra','ContraController@addcontra')->name('addcontra');
    // Account report Controller 
    Route::get('alldep','AccReoprtController@index')->name('alldep');
    Route::post('addalldep','AccReoprtController@alldipreport')->name('addalldep');
    Route::get('depwise','AccReoprtController@dipwise')->name('depwise');
    Route::get('ledwise','AccReoprtController@ledwise')->name('ledwise');
    Route::get('fund','AccReoprtController@fund')->name('fund');
    Route::post('fundstate','AccReoprtController@fundstate')->name('fundstate');
    Route::post('addepwise','AccReoprtController@addepwise')->name('addepwise');
    Route::post('ledgerwise','AccReoprtController@ledgerwise')->name('ledgerwise');
    // Cash Book
    Route::get('cashb','AccReoprtController@cashb')->name('cashb');
    Route::post('cashbook','AccReoprtController@cashbook')->name('cashbook');
    //bankbook
    Route::get('bankb','AccReoprtController@bankb')->name('bankb');
    Route::post('bankbook','AccReoprtController@bankbook')->name('bankbook');
});
Route::group(['middleware' => 'auth'], function ()
{
 Route::resource('devotee','DevoteeController');
});
Route::group(['middleware' => 'auth','prefix' => 'departmental'], function ()
{
 Route::get('create','DepartmentalController@inf')->name('depcreate');
Route::post('addinf','DepartmentalController@addinf')->name('addinf');
Route::get('trans','DepartmentalController@trans')->name('deptrans');
Route::post('addtrans','DepartmentalController@addtrans')->name('adddeptrans');
Route::get('reportq','DepartmentalController@reportq')->name('reportq');
Route::post('rtodb','DepartmentalController@rtodb')->name('rtodb');
});

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
     <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>ISKCON- @yield('title') page</title>
<link rel="stylesheet" href="{{asset('css/parsley.css')}}">
<link href="{{asset('css/app.css')}}" rel="stylesheet">
 @yield('stylesheet')
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">ISKCON SOFTWARE</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
            <!-- Authentication Links -->
             @if (Auth::guest())
                <li><a href="{{ route('login') }}">Login</a></li>
                
            @else
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                         {{ Auth::user()->name }}
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        
                        <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();"><i class="fa fa-sign-out fa-fw"></i>Logout</a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                             {{ csrf_field() }}
                         </form>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
            @endif
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="#!"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>Stock<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{route('customer')}}">Add Customer</a>
                                </li>
                                <li>
                                    <a href="#!">Add New <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="{{route('book')}}">Add New Book</a>
                                        </li>
                                        <li>
                                            <a href="{{route('para')}}">Add New Para</a>
                                        </li>
                                        
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                                <li>
                                    <a href="#!">Purchase <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="{{route('purchasebook')}}">Purchases Of Book</a>
                                        </li>
                                        <li>
                                            <a href="{{route('purchasepara')}}">Purchases Of Para</a>
                                        </li>
                                        
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                                <li>
                                    <a href="#">Sales<span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="{{route('salebook')}}">Sales Of Book</a>
                                        </li>
                                        <li>
                                            <a href="{{route('salepara')}}">Sales Of Para</a>
                                        </li>
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                                <li>
                                    <a href="#">Refund <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="{{route('rb')}}">Refund Of Book</a>
                                        </li>
                                        <li>
                                            <a href="{{route('rp')}}">Refund Of Para</a>
                                        </li>
                                        
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                                <li>
                                    <a href="#">Report <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="{{route('bookinq')}}">All book Balance</a>
                                        </li>
                                        <li>
                                            <a href="{{route('parainq')}}">All Para balance</a>
                                        </li>
                                        <li>
                                            <a href="{{route('stat')}}">Customer Status</a>
                                        </li>
                                        <li>
                                            <a href="#">Invoice Wise Report </a>
                                        </li>
                                        
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                                <li>
                                    <a href="#">Transfer to Waste<span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="{{route('tb')}}">Book</a>
                                        </li>
                                        <li>
                                            <a href="{{route('tp')}}">Para</a>
                                        </li>
                                        
                                    </ul>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        
                        <li>
                            <a href="tables.html"><i class="fa fa-table fa-fw"></i> Accounts<span class="fa arrow"></span></a></a>
                            <ul class="nav nav-second-level">
                                        <li>
                                            <a href="{{route('purchasebook')}}">Add New<span class="fa arrow"></span></a></a>
                                            <ul class="nav nav-third-level">
                                                <li>
                                                    <a href="{{route('dep')}}">Add New Department</a>
                                                </li>
                                                <li>
                                                    <a href="{{route('led')}}">Add New Ledger</a>
                                                </li>
                                                
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="{{route('tran')}}">Transection</a>
                                        </li>
                                        <li>
                                            <a href="{{route('alldep')}}">All Department recieved and payment </a>
                                        </li>
                                        <li>
                                            <a href="{{route('depwise')}}">Department Wise recieved and payment </a>
                                        </li>
                                        <li>
                                            <a href="{{route('ledwise')}}">Ledger Wise recieved and payment </a>
                                        </li>
                                        <li>
                                            <a href="{{route('fund')}}">Fund Statement</a>
                                        </li>
                                        <li>
                                            <a href="{{route('cashb')}}">Cash-book Report </a>
                                        </li>
                                        <li>
                                            <a href="{{route('bankb')}}">Bank-book Report </a>
                                        </li>
                                    </ul>
                        </li>
                        <li>
                            <a href="#!"><i class="fa fa-edit fa-fw"></i> Department's Account<span class="fa arrow"></span></a></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{route('depcreate')}}">Add Information</a>
                                </li>
                                <li>
                                    <a href="{{route('deptrans')}}">Transection</a>
                                </li>
                                <li>
                                    <a href="{{route('reportq')}}">Report</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> Devotee<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{route('devotee.create')}}">Add New Devotee</a>
                                </li>
                                <li>
                                    <a href="{{route('devotee.index')}}">Devotee List</a>
                                </li>
                                
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        
                        <li>
                            <a href="#"><i class="fa fa-files-o fa-fw"></i>Super Admin<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="blank.html">General Info</a>
                                </li>
                                <li>
                                    <a href="login.html">Permission</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">@yield('pageheader')</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              @yield('content')  
            </div>
            <!-- /.row -->
          
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    
    <!-- Custom Theme JavaScript -->
     <script src="{{asset('js/vue.js')}}"></script>
     <script src="{{asset('js/app.js')}}"></script>
     <script src="{{asset('js/parsley.min.js')}}"></script>
     <script src="{{asset('js/jquery-ui.min.js')}}"></script>
    @yield('javascript')

</body>

</html>